name: CD

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

############################
# STAGE 1 — ACC
############################
stages:
- stage: ACC
  displayName: Deploy to ACC

  jobs:
  - job: Deploy_ACC
    displayName: ACC Deployment

    steps:
    - checkout: self
      persistCredentials: true

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        databricks --version
      displayName: Install Databricks CLI

    # Configure Databricks
    - script: |
        mkdir -p ~/.databricks
        cat > ~/.databrickscfg << EOF
        [DEFAULT]
        host = $(DATABRICKS_HOST)
        client_id = $(DATABRICKS_CLIENT_ID)
        client_secret = $(DATABRICKS_CLIENT_SECRET)
        EOF
      displayName: Configure Databricks

    # Install uv
    - script: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "##vso[task.prependpath]$HOME/.local/bin"
      displayName: Install uv

    # Deploy bundle to ACC
    - script: |
        export DATABRICKS_BUNDLE_ENV=acc

        databricks bundle deploy \
          --var="git_sha=$(Build.SourceVersion)" \
          --var="branch=$(Build.SourceBranchName)"
      displayName: Bundle Deploy ACC

    # Run bundle in ACC
    # - script: |
    #     export DATABRICKS_BUNDLE_ENV=acc
    #     databricks bundle run deployment
    #   displayName: Bundle Run ACC


############################
# STAGE 2 — PRD
############################
- stage: PRD
  displayName: Deploy to PRD
  dependsOn: ACC
  condition: succeeded()   # 👈 only run if ACC succeeds

  jobs:
  - job: Deploy_PRD
    displayName: PRD Deployment

    steps:
    - checkout: self
      persistCredentials: true

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: Install Databricks CLI

    # Configure Databricks
    - script: |
        mkdir -p ~/.databricks
        cat > ~/.databrickscfg << EOF
        [DEFAULT]
        host = $(DATABRICKS_HOST)
        client_id = $(DATABRICKS_CLIENT_ID)
        client_secret = $(DATABRICKS_CLIENT_SECRET)
        EOF
      displayName: Configure Databricks

    # Install uv
    - script: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "##vso[task.prependpath]$HOME/.local/bin"
      displayName: Install uv

    # Deploy bundle to PRD
    - script: |
        export DATABRICKS_BUNDLE_ENV=prd

        databricks bundle deploy\
          --var="git_sha=$(Build.SourceVersion)" \
          --var="branch=$(Build.SourceBranchName)"
      displayName: Bundle Deploy PRD

    # Run bundle in PRD
    - script: |
        export DATABRICKS_BUNDLE_ENV=prd
        databricks bundle run production
      displayName: Bundle Run PRD
