trigger:
  - master

# PR trigger to master
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON_VERSION: "3.11"

steps:

# Checkout with full git history
- checkout: self
  fetchDepth: 0
  persistCredentials: true

# Select Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)
  displayName: "Use Python $(PYTHON_VERSION)"

# Install uv
- script: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
    echo "##vso[task.prependpath]$HOME/.local/bin"
    uv --version
  displayName: "Install uv"

# Cache uv dependencies
- task: Cache@2
  inputs:
    key: 'uv | "$(Agent.OS)" | uv.lock'
    restoreKeys: |
      uv | "$(Agent.OS)"
    path: ~/.cache/uv
  displayName: "Cache uv"

# Install dependencies
- script: |
    uv sync --extra test
  displayName: "Install dependencies"

# Create git tag from version.txt
- script: |
    VERSION=$(cat version.txt)
    echo "Version: $VERSION"

    git config user.email "ci@local"
    git config user.name "CI"

    git tag $VERSION || echo "Tag already exists"
  displayName: "Git tag from version.txt"

# Run pre-commit
- script: |
    uv run pre-commit run --all-files || true
  displayName: "Run pre-commit"

# Run pytest
- script: |
    uv run pytest -m "not ci_exclude"
  displayName: "Run pytest"
